<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Customer;
use Illuminate\Support\Facades\Hash;

class CustomersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $customers = [
            [
                'full_name' => 'User1',
                'phone_number' => '0987654322',
                'email' => 'user1@gmail.com',
                'address' => '123 Đường Lê Lợi, Quận 1, TP. Hồ Chí Minh',
                'pet_name' => 'Mít',
                'pet_type' => 'Chó',
                'pet_age' => 3,
                'preferred_products' => 'Thức ăn cho chó, Đồ chơi cho chó',
                'last_purchase_date' => '2024-01-15 14:30:00',
                'total_spent' => 1500000,
                'notes' => 'Khách hàng thân thiết',
                'password' => Hash::make("112233"),
                'role' => 0,
            ],
            [
                'full_name' => 'Admin1',
                'phone_number' => '0912345679',
                'email' => 'admin1@gmail.com',
                'address' => '456 Đường Hai Bà Trưng, Quận 3, TP. Hồ Chí Minh',
                'pet_name' => 'Mèo Mướp',
                'pet_type' => 'Mèo',
                'pet_age' => 2,
                'preferred_products' => 'Thức ăn cho mèo, Cát vệ sinh cho mèo',
                'last_purchase_date' => '2024-03-22 10:15:00',
                'total_spent' => 800000,
                'notes' => 'Ưu tiên vận chuyển nhanh',
                'password' => Hash::make('112233'),
                'role' => 1,
            ],
            [
                'full_name' => 'User2',
                'phone_number' => '0987654323',
                'email' => 'user2@gmail.com',
                'address' => '789 Đường Nguyễn Trãi, Quận 5, TP. Hồ Chí Minh',
                'pet_name' => 'Cún',
                'pet_type' => 'Chó',
                'pet_age' => 4,
                'preferred_products' => 'Thức ăn cho chó, Đồ chơi cho chó',
                'last_purchase_date' => '2024-02-10 16:30:00',
                'total_spent' => 2000000,
                'notes' => 'Thích sản phẩm cao cấp',
                'password' => Hash::make("112233"),
                'role' => 0,
            ],
            [
                'full_name' => 'Admin2',
                'phone_number' => '0912345680',
                'email' => 'admin2@gmail.com',
                'address' => '345 Đường Bùi Viện, Quận 1, TP. Hồ Chí Minh',
                'pet_name' => 'Mèo Mun',
                'pet_type' => 'Mèo',
                'pet_age' => 1,
                'preferred_products' => 'Thức ăn cho mèo, Cát vệ sinh cho mèo',
                'last_purchase_date' => '2024-04-05 18:00:00',
                'total_spent' => 600000,
                'notes' => 'Ưa chuộng đồ giảm giá',
                'password' => Hash::make('112233'),
                'role' => 1,
            ],
            [
                'full_name' => 'User3',
                'phone_number' => '0987654324',
                'email' => 'user3@gmail.com',
                'address' => '567 Đường Cộng Hòa, Quận Tân Bình, TP. Hồ Chí Minh',
                'pet_name' => 'Gấu',
                'pet_type' => 'Chó',
                'pet_age' => 5,
                'preferred_products' => 'Thức ăn cho chó, Đồ chơi cho chó',
                'last_purchase_date' => '2024-05-18 09:00:00',
                'total_spent' => 2500000,
                'notes' => 'Luôn chọn sản phẩm chất lượng cao',
                'password' => Hash::make("112233"),
                'role' => 0,
            ],
            [
                'full_name' => 'Admin3',
                'phone_number' => '0912345681',
                'email' => 'admin3@gmail.com',
                'address' => '321 Đường Điện Biên Phủ, Quận Bình Thạnh, TP. Hồ Chí Minh',
                'pet_name' => 'Mèo Bông',
                'pet_type' => 'Mèo',
                'pet_age' => 3,
                'preferred_products' => 'Thức ăn cho mèo, Cát vệ sinh cho mèo',
                'last_purchase_date' => '2024-06-25 12:30:00',
                'total_spent' => 1200000,
                'notes' => 'Ưa chuộng sản phẩm khuyến mãi',
                'password' => Hash::make('112233'),
                'role' => 1,
            ],
            [
                'full_name' => 'User4',
                'phone_number' => '0987654325',
                'email' => 'user4@gmail.com',
                'address' => '123 Đường Nguyễn Huệ, Quận 1, TP. Hồ Chí Minh',
                'pet_name' => 'Panda',
                'pet_type' => 'Chó',
                'pet_age' => 2,
                'preferred_products' => 'Thức ăn cho chó, Đồ chơi cho chó',
                'last_purchase_date' => '2024-07-11 14:00:00',
                'total_spent' => 1800000,
                'notes' => 'Thích đồ chơi cho thú cưng',
                'password' => Hash::make("112233"),
                'role' => 0,
            ],
            [
                'full_name' => 'Admin4',
                'phone_number' => '0912345682',
                'email' => 'admin4@gmail.com',
                'address' => '456 Đường Nam Kỳ Khởi Nghĩa, Quận 3, TP. Hồ Chí Minh',
                'pet_name' => 'Mèo Nâu',
                'pet_type' => 'Mèo',
                'pet_age' => 4,
                'preferred_products' => 'Thức ăn cho mèo, Cát vệ sinh cho mèo',
                'last_purchase_date' => '2024-08-30 17:00:00',
                'total_spent' => 1500000,
                'notes' => 'Ưu tiên mua đồ cho mèo',
                'password' => Hash::make('112233'),
                'role' => 1,
            ],
            [
                'full_name' => 'User5',
                'phone_number' => '0987654326',
                'email' => 'user5@gmail.com',
                'address' => '789 Đường Phạm Ngọc Thạch, Quận 3, TP. Hồ Chí Minh',
                'pet_name' => 'Thỏ',
                'pet_type' => 'Thỏ',
                'pet_age' => 1,
                'preferred_products' => 'Cỏ cho thỏ, Chuồng thỏ',
                'last_purchase_date' => '2024-09-15 08:30:00',
                'total_spent' => 900000,
                'notes' => 'Mua đồ ăn cho thỏ thường xuyên',
                'password' => Hash::make("112233"),
                'role' => 0,
            ],
            [
                'full_name' => 'Admin5',
                'phone_number' => '0912345683',
                'email' => 'admin5@gmail.com',
                'address' => '321 Đường Nguyễn Trãi, Quận 5, TP. Hồ Chí Minh',
                'pet_name' => 'Mèo Mập',
                'pet_type' => 'Mèo',
                'pet_age' => 5,
                'preferred_products' => 'Thức ăn cho mèo, Cát vệ sinh cho mèo',
                'last_purchase_date' => '2024-10-10 15:45:00',
                'total_spent' => 1100000,
                'notes' => 'Ưu tiên đồ giảm giá cho mèo',
                'password' => Hash::make('112233'),
                'role' => 1,
            ],
            [
                'full_name' => 'User6',
                'phone_number' => '0987654327',
                'email' => 'user6@gmail.com',
                'address' => '456 Đường Lê Văn Sỹ, Quận 3, TP. Hồ Chí Minh',
                'pet_name' => 'Chim Sẻ',
                'pet_type' => 'Chim',
                'pet_age' => 2,
                'preferred_products' => 'Cám cho chim, Lồng chim',
                'last_purchase_date' => '2024-11-05 17:00:00',
                'total_spent' => 500000,
                'notes' => 'Chuyên dùng cám cho chim',
                'password' => Hash::make("112233"),
                'role' => 0,
            ],
            [
                'full_name' => 'Admin6',
                'phone_number' => '0912345684',
                'email' => 'admin6@gmail.com',
                'address' => '123 Đường Hai Bà Trưng, Quận 1, TP. Hồ Chí Minh',
                'pet_name' => 'Mèo Béo',
                'pet_type' => 'Mèo',
                'pet_age' => 6,
                'preferred_products' => 'Thức ăn cho mèo, Cát vệ sinh cho mèo',
                'last_purchase_date' => '2024-12-01 16:30:00',
                'total_spent' => 2000000,
                'notes' => 'Chỉ mua đồ cao cấp',
                'password' => Hash::make('112233'),
                'role' => 1,
            ],
            [
                'full_name' => 'User7',
                'phone_number' => '0987654328',
                'email' => 'user7@gmail.com',
                'address' => '789 Đường Hồ Chí Minh, Quận Tân Phú, TP. Hồ Chí Minh',
                'pet_name' => 'Cún Con',
                'pet_type' => 'Chó',
                'pet_age' => 3,
                'preferred_products' => 'Thức ăn cho chó, Đồ chơi cho chó',
                'last_purchase_date' => '2024-12-20 15:00:00',
                'total_spent' => 1800000,
                'notes' => 'Luôn chọn đồ an toàn cho thú cưng',
                'password' => Hash::make("112233"),
                'role' => 0,
            ],
            [
                'full_name' => 'Admin7',
                'phone_number' => '0912345685',
                'email' => 'admin7@gmail.com',
                'address' => '456 Đường Nguyễn Văn Cừ, Quận 4, TP. Hồ Chí Minh',
                'pet_name' => 'Mèo Vằn',
                'pet_type' => 'Mèo',
                'pet_age' => 2,
                'preferred_products' => 'Thức ăn cho mèo, Cát vệ sinh cho mèo',
                'last_purchase_date' => '2025-01-10 11:00:00',
                'total_spent' => 1600000,
                'notes' => 'Chuyên mua đồ giảm giá cho mèo',
                'password' => Hash::make('112233'),
                'role' => 1,
            ],
            [
                'full_name' => 'User8',
                'phone_number' => '0987654329',
                'email' => 'user8@gmail.com',
                'address' => '123 Đường Võ Thị Sáu, Quận 2, TP. Hồ Chí Minh',
                'pet_name' => 'Thỏ Trắng',
                'pet_type' => 'Thỏ',
                'pet_age' => 4,
                'preferred_products' => 'Cỏ cho thỏ, Chuồng thỏ',
                'last_purchase_date' => '2025-02-05 14:00:00',
                'total_spent' => 700000,
                'notes' => 'Mua đồ cho thỏ thường xuyên',
                'password' => Hash::make("112233"),
                'role' => 0,
            ],
            [
                'full_name' => 'Admin8',
                'phone_number' => '0912345686',
                'email' => 'admin8@gmail.com',
                'address' => '456 Đường Trần Hưng Đạo, Quận 5, TP. Hồ Chí Minh',
                'pet_name' => 'Mèo Xám',
                'pet_type' => 'Mèo',
                'pet_age' => 5,
                'preferred_products' => 'Thức ăn cho mèo, Cát vệ sinh cho mèo',
                'last_purchase_date' => '2025-03-25 13:45:00',
                'total_spent' => 1300000,
                'notes' => 'Ưa chuộng sản phẩm khuyến mãi',
                'password' => Hash::make('112233'),
                'role' => 1,
            ],
        ];

        foreach ($customers as $customer) {
            Customer::insert($customer);
        }
    }
}
